version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MuRaD198852_Mmm
      POSTGRES_DB: market
    ports:
      - "5545:5432"
