server:
  port: 8801
  tomcat:
    threads:
      max: 2
spring:
  application:
    name: eureka
  main:
    sources: -Xmx100m
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8801/eureka


logging:
  level:
    com:
      netflix:
        eureka: off
        discovery: off