server:
  port: 8800
  tomcat:
    threads:
      max: 2
spring:
  application:
    name: getaway
  config:
    import: optional:configserver:http://localhost:8802
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://3.78.84.198/"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "Authorization, Content-Type"
            allowCredentials: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Methods Access-Control-Allow-Headers Access-Control-Allow-Origin
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: operation
          uri: lb://operation
          predicates:
            - Path=/product/**
            - Path=/category/**
            - Path=/subcategories/**
        - id: cart
          uri: lb://cart
          predicates:
            - Path=/cart/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka
