server:
  port: 8802
  tomcat:
    threads:
      max: 2

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/murad-java/OnlineMarketConfig

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka